# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SLCC1 <- function(indexy, y, z, x, weights, wtilde, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-4) {
    .Call(`_SAESLCC_SLCC1`, indexy, y, z, x, weights, wtilde, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

SLCC2 <- function(indexy, y, x, weights, wtilde, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-4) {
    .Call(`_SAESLCC_SLCC2`, indexy, y, x, weights, wtilde, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

SLCC3 <- function(indexy, y, x, group, weights, wtilde, betam0, nu = 1, gam = 3, lam = 0.5, maxiter = 1000L, tolabs = 1e-4, tolrel = 1e-4) {
    .Call(`_SAESLCC_SLCC3`, indexy, y, x, group, weights, wtilde, betam0, nu, gam, lam, maxiter, tolabs, tolrel)
}

cal_initialr <- function(indexy, y, z, x, wtilde, lam0 = 0.0001) {
    .Call(`_SAESLCC_cal_initialr`, indexy, y, z, x, wtilde, lam0)
}

cal_initialrx <- function(indexy, y, x, wtilde, lam0 = 0.0001) {
    .Call(`_SAESLCC_cal_initialrx`, indexy, y, x, wtilde, lam0)
}

getgroup <- function(deltam, n, tol = 1e-4) {
    .Call(`_SAESLCC_getgroup`, deltam, n, tol)
}

ngetgroup <- function(b2value, n, tol = 1e-3) {
    .Call(`_SAESLCC_ngetgroup`, b2value, n, tol)
}

getorder <- function(Cmat) {
    .Call(`_SAESLCC_getorder`, Cmat)
}

